SET local check_function_bodies = off;

CREATE TABLE "public"."dias_bloqueados" (
  "id"    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fecha" date   NOT NULL,
  CONSTRAINT "dias_bloqueados_fecha_key" UNIQUE (fecha),
  CONSTRAINT "dias_bloqueados_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."dias_bloqueados"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reservas" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fecha"          date                     NOT NULL,
  "aula"           text                     NOT NULL,
  "hora_inicio"    time without time zone   NOT NULL,
  "nombre_cliente" text                     NOT NULL,
  "estado"         text                     NOT NULL DEFAULT 'pendiente'::text,
  "uso"            text                     NOT NULL DEFAULT 'Outros Usos'::text,
  "created_at"     timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reservas_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."reservas"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE POLICY "Permitir lectura en dias_bloqueados" ON "public"."dias_bloqueados"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Permitir todo en reservas" ON "public"."reservas"
  FOR ALL
  TO PUBLIC
  USING (true)
  WITH CHECK (true);

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."dias_bloqueados" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reservas" TO "anon", "authenticated", "postgres", "service_role";

